##EDA Firstcry

In [ ]:
import json

# Read the JSON file
with open('marketplace/firstcry.json', 'r') as file:
    data = json.load(file)

# Display the data
print(data)

#Convert file json to csv, more proper table

In [ ]:
import json
import csv

# Load the JSON data from the file
with open("marketplace/firstcry.json", "r", encoding="utf-8") as json_file:
    data = json.load(json_file)

# Open a CSV file for writing the transformed data
with open("output.csv", "w", newline="", encoding="utf-8") as csv_file:
    writer = csv.writer(csv_file)
    
    # Write header row
    writer.writerow(["Title", "Product Price", "Original Price", "Club Price", "URL"])
    
    # Process each JSON object in the list
    for idx, obj in enumerate(data):
        titles = obj.get("title", [])
        product_prices = obj.get("product_price", [])
        original_prices = obj.get("original_price", [])
        club_prices = obj.get("club_price", [])
        url = obj.get("url", "")
        
        # Determine the minimum length to avoid index errors
        min_len = min(len(titles), len(product_prices), len(original_prices), len(club_prices))
        if not (len(titles) == len(product_prices) == len(original_prices) == len(club_prices)):
            print(f"Warning: Data mismatch in entry {idx+1}. Only processing first {min_len} items.")
        
        # Write each product's details using zip
        for title, prod_price, orig_price, club_price in zip(titles, product_prices, original_prices, club_prices):
            writer.writerow([title, prod_price, orig_price, club_price, url])

print("CSV file 'output.csv' has been created successfully.")

In [ ]:

import pandas as pd
df = pd.read_csv('output_firstcry.csv')
df.head(10)

In [ ]:
df.duplicated(subset=['Title'], keep='first').sum()

In [ ]:

df.drop_duplicates(subset=['Title'], keep='first', inplace=True)
df.duplicated(subset=['Title'], keep='first').sum()

In [ ]:
#save the cleaned DataFrame to a new CSV file
df.to_csv('output_firstcry_cleaned.csv', index=False)

##Snooplay

In [5]:
import pandas as pd
df_snooplay = pd.read_csv("marketplace/snooplay.csv")
df_snooplay.head(10)

,title,product_price,original_price,price_w_discount,url
0,Global Play Tent House with Wheels (1-7 Years),₹ 832.50,"MRP: ₹ 1,125",Best Price ₹ 749.25,https://snooplay.in/products/global-play-tent-...
1,"Football with Air Pump & Pin - Size 1 Mini, 12...",₹ 349,MRP: ₹ 599,Best Price ₹ 314.10,https://snooplay.in/products/football-with-air...
2,Nippon Cricket Set with Bag (1.5-3 Years),₹ 155,MRP: ₹ 360,Best Price ₹ 139.50,https://snooplay.in/products/nippon-cricket-se...
3,Flexible Swing Seat with Metal Triangle Hook w...,"₹ 3,499","MRP: ₹ 6,999","Best Price ₹ 3,149.10",https://snooplay.in/products/flexible-swing-se...
4,Zoo Little Kid Backpack-Shark,"₹ 2,159","MRP: ₹ 2,399","Best Price ₹ 1,943.10",https://snooplay.in/products/zoo-little-kid-ba...
5,Naturally Playful Picnic Table With Umbrella f...,"₹ 26,999.10","MRP: ₹ 29,999","Best Price ₹ 24,299.19",https://snooplay.in/products/naturally-playful...
6,5 Column Geometric Shape Sorter Stacking Puzzl...,₹ 449,MRP: ₹ 799,Best Price ₹ 404.10,https://snooplay.in/products/5-column-geometri...
7,Color Sorting Slide Puzzle Game for Kids | 4 C...,₹ 649,"MRP: ₹ 1,399",Best Price ₹ 584.10,https://snooplay.in/products/slide-puzzle-brai...
8,Remote Controlled Bike A512 - 360 Degree Rotat...,"₹ 2,550","MRP: ₹ 3,100",NaN,https://snooplay.in/products/remote-controlled...
9,Wooden Domino Toy - 100 Pieces (3-7 Years),₹ 299,MRP: ₹ 599,Best Price ₹ 269.10,https://snooplay.in/products/wooden-domino-toy...

In [14]:

#remove  ₹ and change the datatype to int
df_snooplay['product_price'] = df_snooplay['product_price'].str.replace('₹', '').str.replace(',', '')
df_snooplay.head(10)

,title,product_price,original_price,price_w_discount,url
0,Global Play Tent House with Wheels (1-7 Years),832.50,"MRP: ₹ 1,125",Best Price ₹ 749.25,https://snooplay.in/products/global-play-tent-...
1,"Football with Air Pump & Pin - Size 1 Mini, 12...",349,MRP: ₹ 599,Best Price ₹ 314.10,https://snooplay.in/products/football-with-air...
2,Nippon Cricket Set with Bag (1.5-3 Years),155,MRP: ₹ 360,Best Price ₹ 139.50,https://snooplay.in/products/nippon-cricket-se...
3,Flexible Swing Seat with Metal Triangle Hook w...,3499,"MRP: ₹ 6,999","Best Price ₹ 3,149.10",https://snooplay.in/products/flexible-swing-se...
4,Zoo Little Kid Backpack-Shark,2159,"MRP: ₹ 2,399","Best Price ₹ 1,943.10",https://snooplay.in/products/zoo-little-kid-ba...
5,Naturally Playful Picnic Table With Umbrella f...,26999.10,"MRP: ₹ 29,999","Best Price ₹ 24,299.19",https://snooplay.in/products/naturally-playful...
6,5 Column Geometric Shape Sorter Stacking Puzzl...,449,MRP: ₹ 799,Best Price ₹ 404.10,https://snooplay.in/products/5-column-geometri...
7,Color Sorting Slide Puzzle Game for Kids | 4 C...,649,"MRP: ₹ 1,399",Best Price ₹ 584.10,https://snooplay.in/products/slide-puzzle-brai...
8,Remote Controlled Bike A512 - 360 Degree Rotat...,2550,"MRP: ₹ 3,100",NaN,https://snooplay.in/products/remote-controlled...
9,Wooden Domino Toy - 100 Pieces (3-7 Years),299,MRP: ₹ 599,Best Price ₹ 269.10,https://snooplay.in/products/wooden-domino-toy...

In [15]:
df_snooplay.tail(10)

,title,product_price,original_price,price_w_discount,url
131,Spyrosity Super Quiller Tool (8-13 Years),549,MRP: ₹ 599,Best Price ₹ 494.10,https://snooplay.in/products/spyrosity-super-q...
132,Stamp Art - Mandala Art (8-14 Years),649,MRP: ₹ 699,Best Price ₹ 584.10,https://snooplay.in/products/stamp-art-mandala...
133,Window Art - Unicorn (5-10 Years),649,MRP: ₹ 699,Best Price ₹ 584.10,https://snooplay.in/products/window-art-unicor...
134,Mapology India with Capitals Flashcards & Puzz...,699,MRP: ₹ 799,Best Price ₹ 629.10,https://snooplay.in/products/mapology-india-wi...
135,Mapology History Quest India-Dice Game (10-15 ...,799,MRP: ₹ 899,Best Price ₹ 719.10,https://snooplay.in/products/mapology-history-...
136,Mapology History Quest India-Dice Game (10-15 ...,799,MRP: ₹ 899,Best Price ₹ 719.10,https://snooplay.in/products/mapology-history-...
137,Mapology India with Capitals Flashcards & Puzz...,699,MRP: ₹ 799,Best Price ₹ 629.10,https://snooplay.in/products/mapology-india-wi...
138,Stamp Art - Mandala Art (8-14 Years),649,MRP: ₹ 699,Best Price ₹ 584.10,https://snooplay.in/products/stamp-art-mandala...
139,Spyrosity Super Quiller Tool (8-13 Years),549,MRP: ₹ 599,Best Price ₹ 494.10,https://snooplay.in/products/spyrosity-super-q...
140,Window Art - Unicorn (5-10 Years),649,MRP: ₹ 699,Best Price ₹ 584.10,https://snooplay.in/products/window-art-unicor...

C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_snooplay['product_price'][i] = float(df_snooplay['product_price'][i])
C:\Users\rjriz\AppData\Local\Temp\ipykernel_13508\2619397005.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!

dtype('O')

In [19]:
import re

# Extract only numbers from the 'product_price' column
df_snooplay['product_price'] = df_snooplay['product_price'].str.extract(r'(\d+)', expand=False).astype(float)

# Display the updated DataFrame
df_snooplay.head(10)

AttributeError: Can only use .str accessor with string values!

In [20]:
import pandas as pd

def convert_price_to_float(price_string):
    """
    Converts a price string to a float, handling various formats.

    Args:
        price_string (str): The price string to convert.

    Returns:
        float: The converted price as a float, or None if conversion fails.
    """
    if not isinstance(price_string, str):
        return None  # or return the original value

    try:
        # Remove currency symbols, commas, and other non-numeric characters
        cleaned_price = ''.join(c for c in price_string if c.isdigit() or c == '.')

        # Convert to float
        return float(cleaned_price)
    except ValueError:
        return None  # or return the original value

df_snooplay = pd.read_csv("marketplace/snooplay.csv")

# Apply the conversion function to the 'product_price' column
# Only apply the function to string values
df_snooplay['product_price'] = df_snooplay['product_price'].apply(lambda x: convert_price_to_float(x) if isinstance(x, str) else x)

df_snooplay.head(10)

,title,product_price,original_price,price_w_discount,url
0,Global Play Tent House with Wheels (1-7 Years),832.5,"MRP: ₹ 1,125",Best Price ₹ 749.25,https://snooplay.in/products/global-play-tent-...
1,"Football with Air Pump & Pin - Size 1 Mini, 12...",349.0,MRP: ₹ 599,Best Price ₹ 314.10,https://snooplay.in/products/football-with-air...
2,Nippon Cricket Set with Bag (1.5-3 Years),155.0,MRP: ₹ 360,Best Price ₹ 139.50,https://snooplay.in/products/nippon-cricket-se...
3,Flexible Swing Seat with Metal Triangle Hook w...,3499.0,"MRP: ₹ 6,999","Best Price ₹ 3,149.10",https://snooplay.in/products/flexible-swing-se...
4,Zoo Little Kid Backpack-Shark,2159.0,"MRP: ₹ 2,399","Best Price ₹ 1,943.10",https://snooplay.in/products/zoo-little-kid-ba...
5,Naturally Playful Picnic Table With Umbrella f...,26999.1,"MRP: ₹ 29,999","Best Price ₹ 24,299.19",https://snooplay.in/products/naturally-playful...
6,5 Column Geometric Shape Sorter Stacking Puzzl...,449.0,MRP: ₹ 799,Best Price ₹ 404.10,https://snooplay.in/products/5-column-geometri...
7,Color Sorting Slide Puzzle Game for Kids | 4 C...,649.0,"MRP: ₹ 1,399",Best Price ₹ 584.10,https://snooplay.in/products/slide-puzzle-brai...
8,Remote Controlled Bike A512 - 360 Degree Rotat...,2550.0,"MRP: ₹ 3,100",NaN,https://snooplay.in/products/remote-controlled...
9,Wooden Domino Toy - 100 Pieces (3-7 Years),299.0,MRP: ₹ 599,Best Price ₹ 269.10,https://snooplay.in/products/wooden-domino-toy...

In [21]:

# Apply the conversion function to the 'original_price' column
# Only apply the function to string values
df_snooplay['original_price'] = df_snooplay['original_price'].apply(lambda x: convert_price_to_float(x) if isinstance(x, str) else x)
df_snooplay.head(10)

,title,product_price,original_price,price_w_discount,url
0,Global Play Tent House with Wheels (1-7 Years),832.5,1125.0,Best Price ₹ 749.25,https://snooplay.in/products/global-play-tent-...
1,"Football with Air Pump & Pin - Size 1 Mini, 12...",349.0,599.0,Best Price ₹ 314.10,https://snooplay.in/products/football-with-air...
2,Nippon Cricket Set with Bag (1.5-3 Years),155.0,360.0,Best Price ₹ 139.50,https://snooplay.in/products/nippon-cricket-se...
3,Flexible Swing Seat with Metal Triangle Hook w...,3499.0,6999.0,"Best Price ₹ 3,149.10",https://snooplay.in/products/flexible-swing-se...
4,Zoo Little Kid Backpack-Shark,2159.0,2399.0,"Best Price ₹ 1,943.10",https://snooplay.in/products/zoo-little-kid-ba...
5,Naturally Playful Picnic Table With Umbrella f...,26999.1,29999.0,"Best Price ₹ 24,299.19",https://snooplay.in/products/naturally-playful...
6,5 Column Geometric Shape Sorter Stacking Puzzl...,449.0,799.0,Best Price ₹ 404.10,https://snooplay.in/products/5-column-geometri...
7,Color Sorting Slide Puzzle Game for Kids | 4 C...,649.0,1399.0,Best Price ₹ 584.10,https://snooplay.in/products/slide-puzzle-brai...
8,Remote Controlled Bike A512 - 360 Degree Rotat...,2550.0,3100.0,NaN,https://snooplay.in/products/remote-controlled...
9,Wooden Domino Toy - 100 Pieces (3-7 Years),299.0,599.0,Best Price ₹ 269.10,https://snooplay.in/products/wooden-domino-toy...

In [22]:

# Apply the conversion function to the 'price_w_discount' column
# Only apply the function to string values
df_snooplay['price_w_discount'] = df_snooplay['price_w_discount'].apply(lambda x: convert_price_to_float(x) if isinstance(x, str) else x)
df_snooplay.head(10)

,title,product_price,original_price,price_w_discount,url
0,Global Play Tent House with Wheels (1-7 Years),832.5,1125.0,749.25,https://snooplay.in/products/global-play-tent-...
1,"Football with Air Pump & Pin - Size 1 Mini, 12...",349.0,599.0,314.10,https://snooplay.in/products/football-with-air...
2,Nippon Cricket Set with Bag (1.5-3 Years),155.0,360.0,139.50,https://snooplay.in/products/nippon-cricket-se...
3,Flexible Swing Seat with Metal Triangle Hook w...,3499.0,6999.0,3149.10,https://snooplay.in/products/flexible-swing-se...
4,Zoo Little Kid Backpack-Shark,2159.0,2399.0,1943.10,https://snooplay.in/products/zoo-little-kid-ba...
5,Naturally Playful Picnic Table With Umbrella f...,26999.1,29999.0,24299.19,https://snooplay.in/products/naturally-playful...
6,5 Column Geometric Shape Sorter Stacking Puzzl...,449.0,799.0,404.10,https://snooplay.in/products/5-column-geometri...
7,Color Sorting Slide Puzzle Game for Kids | 4 C...,649.0,1399.0,584.10,https://snooplay.in/products/slide-puzzle-brai...
8,Remote Controlled Bike A512 - 360 Degree Rotat...,2550.0,3100.0,NaN,https://snooplay.in/products/remote-controlled...
9,Wooden Domino Toy - 100 Pieces (3-7 Years),299.0,599.0,269.10,https://snooplay.in/products/wooden-domino-toy...

In [23]:
#save the cleaned DataFrame to a new CSV file
df_snooplay.to_csv('output_snooplay_cleaned.csv', index=False)